"""empty message

Revision ID: 2b5395076f00
Revises: 36d632345c38
Create Date: 2018-05-30 04:12:08.486676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b5395076f00'
down_revision = '36d632345c38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fibonacci_number_requests', sa.Column('number_sequence', sa.Text(), nullable=True))
    op.drop_column('fibonacci_number_requests', 'number_sequencenumber_sequence')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fibonacci_number_requests', sa.Column('number_sequencenumber_sequence', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('fibonacci_number_requests', 'number_sequence')
    # ### end Alembic commands ###
