"""empty message

Revision ID: 36d632345c38
Revises: 5a483e8cbbed
Create Date: 2018-05-30 04:11:25.556189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36d632345c38'
down_revision = '5a483e8cbbed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fibonacci_number_requests', sa.Column('number_sequencenumber_sequence', sa.Text(), nullable=True))
    op.drop_column('fibonacci_number_requests', 'fib_number_sequence')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fibonacci_number_requests', sa.Column('fib_number_sequence', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('fibonacci_number_requests', 'number_sequencenumber_sequence')
    # ### end Alembic commands ###
