"""empty message

Revision ID: 5a483e8cbbed
Revises: 991ea1f9eeb7
Create Date: 2018-05-30 04:09:43.937046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a483e8cbbed'
down_revision = '991ea1f9eeb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fibonacci_number_requests', sa.Column('fib_number_sequence', sa.Text(), nullable=True))
    op.drop_column('fibonacci_number_requests', 'number_sequence')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fibonacci_number_requests', sa.Column('number_sequence', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('fibonacci_number_requests', 'fib_number_sequence')
    # ### end Alembic commands ###
