"""empty message

Revision ID: 991ea1f9eeb7
Revises: 
Create Date: 2018-05-30 04:06:44.501739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '991ea1f9eeb7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fibonacci_number_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fib_number_input', sa.Integer(), nullable=True),
    sa.Column('date_requested', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('number_sequence', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fibonacci_number_requests')
    # ### end Alembic commands ###
